# Generated by Django 5.1.5 on 2025-02-10 08:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_start', models.CharField(choices=[('Delhi', 'Del'), ('Jaipur', 'Jai'), ('Pilani', 'Pil'), ('Kota', 'Kot'), ('Jodhpur', 'Jod'), ('Udaipur', 'Uda')], default='Pilani', max_length=20)),
                ('journey_end', models.CharField(choices=[('Delhi', 'Del'), ('Jaipur', 'Jai'), ('Pilani', 'Pil'), ('Kota', 'Kot'), ('Jodhpur', 'Jod'), ('Udaipur', 'Uda')], default='Delhi', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('fare', models.IntegerField(default=0)),
                ('total_seats', models.IntegerField(default=0)),
                ('available_seats', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('travels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_booked', models.IntegerField(default=0)),
                ('customers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookbus.bus')),
            ],
        ),
    ]
