# Generated by Django 5.1.5 on 2025-02-14 20:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookbus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='stops',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Delhi', 'Del'), ('Jaipur', 'Jai'), ('Pilani', 'Pil'), ('Kota', 'Kot'), ('Jodhpur', 'Jod'), ('Udaipur', 'Uda')], default='Pilani', max_length=20), default=list, size=None),
        ),
    ]
