# Generated by Django 5.1.2 on 2025-02-02 12:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookbus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='journey_end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bus',
            name='journey_start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
