# Generated by Django 5.1.5 on 2025-02-10 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookbus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seats_booked',
        ),
    ]
