# Generated by Django 5.1.2 on 2025-02-02 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookbus', '0002_bus_journey_end_time_bus_journey_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='journey_end_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='journey_start_time',
            new_name='start_time',
        ),
    ]
