# Generated by Django 5.1.5 on 2025-02-10 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookbus', '0002_remove_booking_bus_remove_booking_customers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bookbus.bus'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='seats_booked',
            field=models.IntegerField(default=0),
        ),
    ]
