# Generated by Django 5.1.5 on 2025-02-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookbus', '0003_rename_journey_end_time_bus_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='bus',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
