# Generated by Django 5.1.5 on 2025-02-04 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookbus', '0004_alter_bus_end_time_alter_bus_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='seats',
            new_name='available_seats',
        ),
    ]
