# Generated by Django 5.1.5 on 2025-02-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookbus', '0005_rename_seats_bus_available_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='total_seats',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='bus',
            name='available_seats',
            field=models.IntegerField(default=10),
        ),
    ]
